# Generated by Django 4.0.5 on 2022-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupcreatemodel',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField(help_text='Enter Your username', max_length=50)),
                ('group_location', models.CharField(help_text='Enter Your group_location', max_length=50)),
                ('group_Type', models.CharField(help_text='Enter Your group_type', max_length=50)),
                ('group_describtion', models.TextField(help_text='Enter Your Group_describtion', max_length=50)),
                ('group_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('group_upload_image', models.ImageField(help_text='group_upload_image ', max_length=50, null=True, upload_to='')),
            ],
            options={
                'db_table': 'admin_group_create_details',
            },
        ),
    ]
