# Generated by Django 4.0.5 on 2022-06-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(help_text='Enter Your username', max_length=50)),
                ('user_location', models.TextField(help_text='Enter Your user_location', max_length=50)),
                ('user_mobilenumber', models.BigIntegerField(help_text='Enter Your mobilenumber', max_length=50)),
                ('user_email', models.EmailField(help_text='Enter email', max_length=50)),
                ('user_password', models.CharField(help_text='user_password', max_length=200)),
                ('user_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('user_status', models.CharField(default='Pending', help_text='user_status', max_length=200)),
                ('user_upload_image', models.ImageField(help_text='user_upload_image ', max_length=50, null=True, upload_to='')),
            ],
            options={
                'db_table': 'user_registration_details',
            },
        ),
        migrations.CreateModel(
            name='UserUploadFileModel',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_post_name', models.TextField(help_text='Enter Your upload_post_name', max_length=50)),
                ('upload_describtion', models.TextField(help_text='Enter Your upload_describtion', max_length=50)),
                ('upload_view', models.CharField(help_text='Enter Your upload_view', max_length=50)),
                ('upload_catagories', models.CharField(help_text='upload_catagories', max_length=200)),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('upload_status', models.CharField(default='Pending', help_text='upload_status', max_length=200)),
                ('upload_File', models.ImageField(help_text='upload_File ', max_length=50, null=True, upload_to='')),
            ],
            options={
                'db_table': 'user_upload_file_details',
            },
        ),
    ]
