# Generated by Django 4.0.5 on 2022-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='user_interest',
            field=models.CharField(help_text='user_interest', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='user_type',
            field=models.CharField(help_text='user_type', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='user_password',
            field=models.CharField(help_text='user_password', max_length=200, null=True),
        ),
    ]
