# Generated by Django 4.0.5 on 2022-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userregistrationmodel_user_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupJoin',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_username', models.TextField(help_text='Enter Your upload_post_name', max_length=50)),
                ('group_username_type', models.TextField(help_text='Enter Your upload_describtion', max_length=50)),
                ('group_name', models.CharField(help_text='Enter Your upload_view', max_length=50)),
                ('group_user_join_date', models.DateField(auto_now_add=True, null=True)),
                ('group_status', models.CharField(default='Pending', help_text='upload_status', max_length=200)),
                ('group_user_image', models.ImageField(help_text='upload_File ', max_length=50, null=True, upload_to='')),
            ],
            options={
                'db_table': 'user_join_groups_details',
            },
        ),
    ]
