# Generated by Django 4.0.5 on 2022-06-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_usergroupjoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroupjoin',
            old_name='group_username_type',
            new_name='group_user_type',
        ),
    ]
