# Generated by Django 4.0.5 on 2022-06-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_group_username_type_usergroupjoin_group_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupjoin',
            name='group_describtion',
            field=models.TextField(help_text='Enter Your upload_describtion', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usergroupjoin',
            name='group_image',
            field=models.ImageField(help_text='upload_File ', max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usergroupjoin',
            name='group_type',
            field=models.CharField(default='Pending', help_text='upload_status', max_length=200),
        ),
    ]
