# Generated by Django 4.0.5 on 2022-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_usergroupjoin_group_describtion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupjoin',
            name='group_user_id',
            field=models.CharField(help_text='group_type', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usergroupjoin',
            name='group_type',
            field=models.CharField(help_text='group_type', max_length=200),
        ),
    ]
