# Generated by Django 4.0.5 on 2022-06-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_usergroupjoin_group_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadfilemodel',
            name='upload_catagories',
        ),
        migrations.RemoveField(
            model_name='useruploadfilemodel',
            name='upload_view',
        ),
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='upload_group_name',
            field=models.CharField(help_text='upload_group_name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='upload_user_id',
            field=models.CharField(help_text='upload_user_id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='upload_user_view',
            field=models.CharField(help_text='Enter Your upload_view', max_length=50, null=True),
        ),
    ]
