# Generated by Django 4.0.5 on 2022-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_remove_useruploadfilemodel_upload_catagories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='upload_user_name',
            field=models.CharField(help_text='upload_user_name', max_length=200, null=True),
        ),
    ]
