# Generated by Django 4.0.5 on 2022-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_useruploadfilemodel_search_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdownloads',
            fields=[
                ('download_id', models.AutoField(primary_key=True, serialize=False)),
                ('downloads', models.CharField(help_text='downloads', max_length=50)),
            ],
            options={
                'db_table': 'user_download_details',
            },
        ),
    ]
