# Generated by Django 4.0.5 on 2022-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_userdownloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdownloads',
            name='download_user_id',
            field=models.CharField(help_text='download_user_id', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdownloads',
            name='downloads',
            field=models.CharField(help_text='downloads', max_length=50, null=True),
        ),
    ]
