# Generated by Django 4.0.5 on 2022-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_userdownloads_download_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='upload_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
