# Generated by Django 4.0.5 on 2022-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_useruploadfilemodel_search_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='time',
            field=models.CharField(help_text='upload_user_name', max_length=200, null=True),
        ),
    ]
