# Generated by Django 4.0.5 on 2022-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_useruploadfilemodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadfilemodel',
            name='time',
        ),
        migrations.AddField(
            model_name='usergroupjoin',
            name='group_user_email',
            field=models.EmailField(help_text='group_type', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='admin_user_id',
            field=models.CharField(help_text='admin_user_id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='upload_user_email',
            field=models.EmailField(help_text='upload_user_email', max_length=200, null=True),
        ),
    ]
