# Generated by Django 4.0.5 on 2022-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_remove_useruploadfilemodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfilemodel',
            name='search_rank',
            field=models.BigIntegerField(default=0, help_text='upload_user_name', max_length=200),
        ),
    ]
