# Generated by Django 4.0.5 on 2022-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_useruploadfilemodel_search_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedbacks',
            fields=[
                ('user_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_feeback_name', models.CharField(help_text='user_feeback_name', max_length=50, null=True)),
                ('user_feedback_email', models.EmailField(help_text='user_feedback_email', max_length=50, null=True)),
                ('user_feedback_describtion', models.TextField(help_text='user_feedback_describtion', null=True)),
            ],
            options={
                'db_table': 'user_feeback_details',
            },
        ),
    ]
