# Generated by Django 4.0.5 on 2022-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_userfeedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedbacks',
            name='user_feedback_group_name',
            field=models.CharField(help_text='user_feeback_group_name', max_length=50, null=True),
        ),
    ]
