# Generated by Django 4.0.5 on 2022-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_userfeedbacks_user_feedback_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='upload_user_location',
            field=models.CharField(help_text='upload_group_name', max_length=200, null=True),
        ),
    ]
