# Generated by Django 4.0.5 on 2022-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_useruploadfilemodel_upload_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfilemodel',
            name='group_id',
            field=models.CharField(help_text='group_id', max_length=200, null=True),
        ),
    ]
