# Generated by Django 4.0.5 on 2022-06-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_useruploadfilemodel_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruploadfilemodel',
            old_name='group_id',
            new_name='group_id2',
        ),
    ]
