# Generated by Django 4.0.5 on 2022-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_rename_group_id_useruploadfilemodel_group_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadfilemodel',
            name='group_id2',
        ),
        migrations.AddField(
            model_name='usergroupjoin',
            name='group_id2',
            field=models.CharField(help_text='group_id', max_length=200, null=True),
        ),
    ]
